/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface Ballot2Interface extends utils.Interface {
  functions: {
    "chairman()": FunctionFragment;
    "closeDate()": FunctionFragment;
    "giveRightToVote(address)": FunctionFragment;
    "numPropersal()": FunctionFragment;
    "propersalName(uint256)": FunctionFragment;
    "proposals(uint256)": FunctionFragment;
    "vote(uint256)": FunctionFragment;
    "voters(address)": FunctionFragment;
    "winerName()": FunctionFragment;
    "winingProposal()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "chairman"
      | "closeDate"
      | "giveRightToVote"
      | "numPropersal"
      | "propersalName"
      | "proposals"
      | "vote"
      | "voters"
      | "winerName"
      | "winingProposal"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "chairman", values?: undefined): string;
  encodeFunctionData(functionFragment: "closeDate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "giveRightToVote",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "numPropersal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "propersalName",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "winerName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "winingProposal",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "chairman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeDate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveRightToVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numPropersal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "propersalName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winerName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winingProposal",
    data: BytesLike
  ): Result;

  events: {
    "GiveRightToVote(address)": EventFragment;
    "Vote(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GiveRightToVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Vote"): EventFragment;
}

export interface GiveRightToVoteEventObject {
  voter: string;
}
export type GiveRightToVoteEvent = TypedEvent<
  [string],
  GiveRightToVoteEventObject
>;

export type GiveRightToVoteEventFilter = TypedEventFilter<GiveRightToVoteEvent>;

export interface VoteEventObject {
  sender: string;
  propersal: BigNumber;
  voteCount: BigNumber;
}
export type VoteEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  VoteEventObject
>;

export type VoteEventFilter = TypedEventFilter<VoteEvent>;

export interface Ballot2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Ballot2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chairman(overrides?: CallOverrides): Promise<[string]>;

    closeDate(overrides?: CallOverrides): Promise<[BigNumber]>;

    giveRightToVote(
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    numPropersal(overrides?: CallOverrides): Promise<[BigNumber]>;

    propersalName(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    vote(
      _proposal: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber] & {
        weight: BigNumber;
        voted: boolean;
        vote: BigNumber;
      }
    >;

    winerName(
      overrides?: CallOverrides
    ): Promise<[string] & { winername_: string }>;

    winingProposal(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { winingProposal_: BigNumber }>;
  };

  chairman(overrides?: CallOverrides): Promise<string>;

  closeDate(overrides?: CallOverrides): Promise<BigNumber>;

  giveRightToVote(
    _voter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  numPropersal(overrides?: CallOverrides): Promise<BigNumber>;

  propersalName(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  proposals(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

  vote(
    _proposal: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voters(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, BigNumber] & {
      weight: BigNumber;
      voted: boolean;
      vote: BigNumber;
    }
  >;

  winerName(overrides?: CallOverrides): Promise<string>;

  winingProposal(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    chairman(overrides?: CallOverrides): Promise<string>;

    closeDate(overrides?: CallOverrides): Promise<BigNumber>;

    giveRightToVote(
      _voter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    numPropersal(overrides?: CallOverrides): Promise<BigNumber>;

    propersalName(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    vote(
      _proposal: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber] & {
        weight: BigNumber;
        voted: boolean;
        vote: BigNumber;
      }
    >;

    winerName(overrides?: CallOverrides): Promise<string>;

    winingProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "GiveRightToVote(address)"(voter?: null): GiveRightToVoteEventFilter;
    GiveRightToVote(voter?: null): GiveRightToVoteEventFilter;

    "Vote(address,uint256,uint256)"(
      sender?: null,
      propersal?: null,
      voteCount?: null
    ): VoteEventFilter;
    Vote(sender?: null, propersal?: null, voteCount?: null): VoteEventFilter;
  };

  estimateGas: {
    chairman(overrides?: CallOverrides): Promise<BigNumber>;

    closeDate(overrides?: CallOverrides): Promise<BigNumber>;

    giveRightToVote(
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    numPropersal(overrides?: CallOverrides): Promise<BigNumber>;

    propersalName(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _proposal: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winerName(overrides?: CallOverrides): Promise<BigNumber>;

    winingProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    chairman(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    closeDate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    giveRightToVote(
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    numPropersal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    propersalName(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      _proposal: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    winingProposal(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
