/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ballot1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ballot1__factory>;
    getContractFactory(
      name: "Ballot2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ballot2__factory>;
    getContractFactory(
      name: "Ballot3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ballot3__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "Lock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lock__factory>;

    getContractAt(
      name: "Ballot1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ballot1>;
    getContractAt(
      name: "Ballot2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ballot2>;
    getContractAt(
      name: "Ballot3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ballot3>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "Lock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Lock>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
